### ISSUE TITLE
Panic in Viper library during s3git remote add

### ISSUE THREAD

**Issue by thejacobtaylor** [s3git/s3git-go#4]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x407e3e8]

goroutine 1 [running]:
panic(0x46b69e0, 0xc8200120c0)
    /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/spf13/viper.pflagValue.HasChanged(0x0, 0xc820079bf0)
    /Users/jacob/work/src/github.com/spf13/viper/flags.go:41 +0x8
github.com/spf13/viper.(_Viper).find(0xc8200e62a0, 0x47ad060, 0x8, 0x0, 0x0)
    /Users/jacob/work/src/github.com/spf13/viper/viper.go:738 +0x14a
github.com/spf13/viper.(_Viper).Get(0xc8200e62a0, 0x47ad060, 0x8, 0x0, 0x0)
    /Users/jacob/work/src/github.com/spf13/viper/viper.go:461 +0x10a
github.com/spf13/viper.(_Viper).GetString(0xc8200e62a0, 0x47ad060, 0x8, 0x0, 0x0)
    /Users/jacob/work/src/github.com/spf13/viper/viper.go:539 +0x41
github.com/spf13/viper.GetString(0x47ad060, 0x8, 0x0, 0x0)
    /Users/jacob/work/src/github.com/spf13/viper/viper.go:537 +0x43
github.com/s3git/s3git/cmd.glob.func10(0x4b31aa0, 0xc82019c930, 0x1, 0x7)
    /Users/jacob/work/src/github.com/s3git/s3git/cmd/remote.go:51 +0x147
github.com/spf13/cobra.(_Command).execute(0x4b31aa0, 0xc82019c8c0, 0x7, 0x7, 0x0, 0x0)
    /Users/jacob/work/src/github.com/spf13/cobra/command.go:603 +0x896
github.com/spf13/cobra.(_Command).ExecuteC(0x4b32100, 0x4b31aa0, 0x0, 0x0)
    /Users/jacob/work/src/github.com/spf13/cobra/command.go:689 +0x55c
github.com/spf13/cobra.(_Command).Execute(0x4b32100, 0x0, 0x0)
    /Users/jacob/work/src/github.com/spf13/cobra/command.go:648 +0x2d
github.com/s3git/s3git/cmd.Execute()
    /Users/jacob/work/src/github.com/s3git/s3git/cmd/root.go:54 +0x23
main.main()
    /Users/jacob/work/src/github.com/s3git/s3git/main.go:67 +0x8ec

**Comment by thejacobtaylor** [comment]
Moved to s3git repository
